<a href="https://colab.research.google.com/github/prathmeshtiwari22/Pract/blob/main/torch_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([-62,  75,  -4,  29,  14,   5])

In [3]:
tensor= torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor


tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
arange=torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace= torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace=torch.logspace(start=-10,end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye=torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
a= torch.empty((2,3),dtype=torch.int64)
empty_like=torch.empty_like(a)
empty_like

tensor([[              0,       780516544,       754313120],
        [133166909091872,               0,               0]])

In [12]:
import torch
import time
import numpy as np
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [13]:
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0022933483


In [14]:
# embeddings, torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)



# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [15]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [16]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [17]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [18]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [19]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [20]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [21]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ -9.0304,   2.5445, -10.4020], grad_fn=<SqueezeBackward4>)


In [23]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [24]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[-0.3605,  0.8716,  0.1553, -0.0848, -0.3457, -1.3913],
        [-0.2661, -0.2791,  0.7376,  0.5977,  2.3671,  1.4409],
        [ 0.2536,  0.7407,  0.0312,  1.0818,  0.5911, -0.8778],
        [ 0.3388,  0.7964, -1.9244, -0.6873,  0.4101,  1.9206]],
       grad_fn=<EmbeddingBackward0>)


In [25]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# print(a @ b)
print(torch.matmul(a, b))


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [26]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [27]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [28]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
print(output[:, -1, :])

tensor([[0.5455, 0.1419, 0.3792, 0.0168, 0.8414, 0.9630, 0.8370, 0.6040, 0.1997,
         0.3737],
        [0.0161, 0.8654, 0.4223, 0.7311, 0.2255, 0.3926, 0.3186, 0.4060, 0.1268,
         0.7239],
        [0.7934, 0.6479, 0.1017, 0.5702, 0.6518, 0.9727, 0.4505, 0.4186, 0.5856,
         0.9960],
        [0.8156, 0.1255, 0.1660, 0.7923, 0.3119, 0.7309, 0.6057, 0.8055, 0.9353,
         0.9923],
        [0.3106, 0.0284, 0.3745, 0.6853, 0.8495, 0.3096, 0.8789, 0.0146, 0.9019,
         0.1494],
        [0.3217, 0.4809, 0.6049, 0.3948, 0.3298, 0.3455, 0.7311, 0.1294, 0.9554,
         0.6426],
        [0.0232, 0.9239, 0.5386, 0.6305, 0.9800, 0.8397, 0.0519, 0.7146, 0.4040,
         0.1015],
        [0.9481, 0.6088, 0.8401, 0.7052, 0.9045, 0.6424, 0.9540, 0.3859, 0.2499,
         0.6100],
        [0.0014, 0.5600, 0.5111, 0.4425, 0.2848, 0.3873, 0.8279, 0.8277, 0.8535,
         0.2975],
        [0.6016, 0.3197, 0.7069, 0.1707, 0.3251, 0.9448, 0.1577, 0.9920, 0.5728,
         0.6082],
        [0

IndexError: too many indices for tensor of dimension 2

In [30]:
input = torch.rand((4,8,10))
B,T,C = input.shape
output = input.view(B*T,C)
print(output)
print(output[:, -1, :])

tensor([[0.8852, 0.7660, 0.6586, 0.3908, 0.8285, 0.6577, 0.3559, 0.1685, 0.2433,
         0.5756],
        [0.2297, 0.2839, 0.0409, 0.6713, 0.1809, 0.1507, 0.2929, 0.4756, 0.1946,
         0.0947],
        [0.4487, 0.1633, 0.0799, 0.8572, 0.2679, 0.4532, 0.2865, 0.3355, 0.4799,
         0.7165],
        [0.4111, 0.4048, 0.5919, 0.5102, 0.3189, 0.1308, 0.0268, 0.3567, 0.9097,
         0.7665],
        [0.6518, 0.6990, 0.7011, 0.2785, 0.0987, 0.8695, 0.4237, 0.2334, 0.2174,
         0.8240],
        [0.4483, 0.8667, 0.8333, 0.6895, 0.6228, 0.1393, 0.7095, 0.0552, 0.8277,
         0.4628],
        [0.2108, 0.1455, 0.0778, 0.9181, 0.2043, 0.2134, 0.4471, 0.9523, 0.8930,
         0.0592],
        [0.2430, 0.2563, 0.0194, 0.6228, 0.6792, 0.7797, 0.5894, 0.5065, 0.0236,
         0.4856],
        [0.6295, 0.3710, 0.0852, 0.6992, 0.6372, 0.9591, 0.3105, 0.7229, 0.1474,
         0.9871],
        [0.4751, 0.2232, 0.6406, 0.4314, 0.0438, 0.3082, 0.9781, 0.7869, 0.0648,
         0.7876],
        [0

IndexError: too many indices for tensor of dimension 2

In [31]:
x = torch.tensor([-0.05],dtype=torch.float32)
y = nn.ReLU(x)
print(y)

ReLU(inplace=True)


In [34]:
x = torch.tensor([-0.05],dtype=torch.float32)
y = F.sigmoid(x)
print(y)

tensor([0.4875])


In [35]:
x = torch.tensor([10], dtype=torch.float32)
y = F.tanh(x)
print(y)

tensor([1.])
